global:
  scrape_interval:     5s

  external_labels:
    monitor: 'impacto-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 3s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'

    static_configs:
    - targets: ['localhost:9100']